### ISSUE TITLE
how to access rss entry custom tags?

### ISSUE THREAD

**Issue by richhl** [alexdebril/FeedIoBundle#9]
Here you are the source https://contrataciondelestado.es/sindicacion/sindicacion_283/contratoMenoresPLACSP.atom
¿how am i supposed to access with your library for example the cac-place-ext:ContractFolderStatus tag in any entry?

thx in advance.

**Comment by alexdebril** [comment]
You'll need to use the element iterator, in your case it looks like

$item->getElementIterator('cac-place-ext:ContractFolderStatus');

Let me know if it doesn't work, I just tested this feature through the unit tests.

**Comment by richhl** [comment]
please give me insight, maybe i'm not caching the way your library is supposed to work! I'm trying to grab all details of this syndication https://contrataciondelestado.es/sindicacion/sindicacion_283/contratoMenoresPLACSP.atom . That syndication has conventional atom nodes (title, publicid,...) and other nodes i need to store or deal with as <cac-place-ext:ContractFolderStatus>

I have add the feed with your front en tool http://localhost/feed but now i cannot grab content of <cac-place-ext:ContractFolderStatus> . For example this code returns the feed node title but no result for elements of the node:

```
            $feed = $em->getRepository('Debril\FeedIoBundle\Entity\Feed')
                        ->findOneByUrl("https://contrataciondelestado.es/sindicacion/sindicacion_283/contratoMenoresPLACSP.atom");
            if ( $feed )
            {
                $output->writeln("I have found the source feed");
                $feed->rewind();
                $item = $feed->current();
                $output->writeln($item->getTitle());
                foreach ($item->getAllElements() as $element)
                    $output->writeln($element->getName());              
            } else {
                $output->writeln("I have not found the source feed ".$source);                
            }
```
returns:
```
I have found the source feed
Coordinacion de seguridad y salud de las obras de adecuacion camino de rodadura de las gruas portico del centro logistico de bilbao mercancias
```

**Comment by richhl** [comment]
definitely it seems it is not working, i can see Item persisted, so as Elements but there is not ElementSet persisted so $item->getAllEllements is not going to work. Perhaps a bug in parsing process?

**Comment by alexdebril** [comment]
I can't access the feed, I get a SSL certificate problem. Can you paste the XML document here please ?

**Comment by richhl** [comment]
sure, but you can get rid of thaat problem by includind this in your demo-feedio application app/config/services.yml file:

```
parameters:
#    parameter_name: value
     curl_options:
         verify: false

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     guzzle.client:
         class: GuzzleHttp\Client
         arguments: [%curl_options%]
```
[contratoMenoresPLACSP.txt](https://github.com/alexdebril/FeedIoBundle/files/50595/contratoMenoresPLACSP.txt)
